name: 'QA Agent'
description: 'AI-powered QA Agent for your repository using Strands and Serena'
inputs:
  query:
    description: 'Question to ask the agent'
    required: true
  provider:
    description: 'LLM Provider (openai, anthropic, gemini)'
    required: false
    default: 'openai'
  model:
    description: 'Specific model name'
    required: false
  token:
    description: 'GitHub Token for posting comments'
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        # Note: 'cache: pip' works best if the root repo dictates requirements. 
        # Inside a composite action, caching is more complex, preventing for now to ensure stability.

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run QA Agent
      shell: bash
      env:
        PROVIDER: ${{ inputs.provider }}
        MODEL_NAME: ${{ inputs.model }}
        # Pass the current working directory explicitly if needed, but python default is CWD
      run: |
        python ${{ github.action_path }}/qa_agent.py --query "${{ inputs.query }}" --model "${{ inputs.model }}" > answer.txt

    - name: Post Comment
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        # We need to find the PR/Issue number. In a workflow triggered by issue_comment, 
        # github.event.issue.number is reliable.
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        REPO: ${{ github.repository }}
      run: |
        if [ -f "answer.txt" ]; then
          gh issue comment "$ISSUE_NUMBER" --repo "$REPO" --body-file "answer.txt"
        else
          echo "No answer file generated."
        fi
